stage_1:
  target: stage1.RAE
  params:
    encoder_cls: 'Dinov2withNorm'
    encoder_config_path: 'facebook/dinov2-with-registers-base'
    encoder_input_size: 224
    encoder_params:
      dinov2_path: 'facebook/dinov2-with-registers-base'
      normalize: true
    decoder_config_path: '/scratch/x3411a10/unconditional_diffusion/RAE/configs/decoder/ViTXL'
    pretrained_decoder_path: '/scratch/x3411a10/unconditional_diffusion/RAE/models/decoders/dinov2/wReg_base/ViTXL_n08/model.pt'
    noise_tau: 0.0
    reshape_to_2d: true
    normalization_stat_path: '/scratch/x3411a10/unconditional_diffusion/RAE/models/stats/dinov2/wReg_base/imagenet1k/stat.pt'

stage_2:
  target: vae_rae.models.ddt_vae.DiTwDDTHeadVAECond
  params:
    input_size: 16
    patch_size: 1
    in_channels: 768
    hidden_size: [1152, 2048]
    depth: [28, 2]
    num_heads: [16, 16]
    mlp_ratio: 4.0
    class_dropout_prob: 0.1
    num_classes: 1000
    use_qknorm: false
    use_swiglu: true
    use_rope: true
    use_rmsnorm: true
    wo_shift: false
    use_pos_embed: true
    cond_dim: 0
    cond_dropout_prob: 0.1
  ckpt: '/scratch/x3411a10/unconditional_diffusion/RAE/models/DiTs/Dinov2/wReg_base/ImageNet256/DiTDH-XL/stage2_model.pt'

vae_condition:
  encoder_config_path: 'facebook/dinov2-with-registers-base'
  encoder_input_size: 224
  dinov2_path: 'facebook/dinov2-with-registers-base'
  vae_ckpt: '/scratch/x3411a10/VAE-SIGREG/VAE-SIGREG-SAE/checkpoints/200epoch.pt'
  vae_src_path: '/scratch/x3411a10/VAE-SIGREG/VAE-SIGREG-SAE/src'
  sample_temperature: 1.0

transport:
  params:
    path_type: 'Linear'
    prediction: 'velocity'
    loss_weight: null
    time_dist_type: 'logit-normal_0_1'

misc:
  latent_size: [768, 16, 16]
  num_classes: 1000
  time_dist_shift_dim: 196608
  time_dist_shift_base: 4096

training:
  null_label: 1000
  epochs: 100
  batch_size: 8
  num_workers: 8
  log_interval: 100
  ema_decay: 0.9995
  checkpoint:
    save_mode: ema_only
    save_every_n_epochs: 5
    keep_last_n: 3
  optimizer:
    lr: 1.0e-4
    betas: [0.9, 0.95]
    weight_decay: 0.0

fid_eval:
  enabled: false

grid_eval:
  every_n_epochs: 2

val_eval:
  enabled: true
  every_n_epochs: 1
  val_path: '/scratch/x3411a10/datasets/ffhq256/imagefolder/val'
  batch_size: 8
